AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation Template for creating an ECS cluster with a task definition

Resources:
  TermAssignmentPair:
    Type: AWS::EC2::KeyPair
    Properties:
      KeyName: TermAssignmentPair
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-053b0d53c279acc90
      KeyName: !Ref TermAssignmentPair
      SubnetId: subnet-0ac81a4f0ef66ab1f
      SecurityGroupIds:
        - sg-0a278b719cdcefeae
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -x
          sudo apt-get update -y
          sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt-get update -y
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io
          sudo systemctl start docker
          sudo systemctl enable docker
          sudo usermod -a -G docker ubuntu

Conditions:
  CreateKeyPair: !Not [!Fn::Equals [!Ref TermAssignmentPair, '']]