AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation Template for creating secrets in AWS Secrets Manager

Resources:
  FetchCourseApi:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: fetchCourseApi
      Description: API for fetching courses.
      SecretString: '{"api_key": "https://7ov5vno170.execute-api.us-east-1.amazonaws.com/prod/fetchCourse"}'
  AddSubscriberApi:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: addSubscriberApi
      Description: API for adding subscriber.
      SecretString: '{"api_key": "https://7ov5vno170.execute-api.us-east-1.amazonaws.com/prod/addSubscriberResource"}'
